#!/bin/sh

#export CIMEROOT=/home/aliceb/cesm/cime
#CESMROOT=/home/aliceb/cesm
#OUTPUT=/home/aliceb/CESM_xml2html/toss

export CIMEROOT=/home/ryanj/scripts/cesm2.0.0/cime
CESMROOT=/home/ryanj/scripts/cesm2.0.0
OUTROOT=/home/ryanj/scripts/CESM_xml2html/toss


# CAM UPDATED
echo "CAM"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/components/cam/cime_config/config_component.xml --comp CAM --htmlfile $OUTPUT/cam_input.html --comptag cam_cesm2_0_rel_02 --compversion 6.0

# CICE UPDATED
echo "CICE"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/components/cice/cime_config/config_component.xml --comp CICE --htmlfile $OUTPUT/cice_input.html --comptag cice5_cesm2_0_rel_01 --compversion 5.0

# CISM UPDATED
echo "CISM"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/components/cism/cime_config/config_component.xml --comp CISM --htmlfile $OUTPUT/cism_input.html --comptag release-cesm2.0.01

# CLM - not sure how to handle CLM4.0 since it wasn't a CIME compliant model and doesn't have a unique config_component.xml file
# CLM5 NOT UPDATED AS NOT IN OG
# NEED TO RUN TO GET clm4_5_input OR MANUAL UPDATE
echo "SKIPPING CLM"
#./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/components/clm/cime_config/config_component.xml --comp CLM --htmlfile $OUTPUT/clm5_0_input.html --comptag release-clm5.0.25
#./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/components/clm/cime_config/??? --comp CLM --htmlfile $OUTPUT/clm4_0_input.html --comptag clm4.0.81

# MOSART UPDATED
echo "MOSART"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/components/mosart/cime_config/config_component.xml --comp MOSART --htmlfile $OUTPUT/mosart_input.html --comptag release-cesm2.0.00

# POP2 UPDATED
# pop namelist required *a lot* of manual edits to get it parse through CIME tools and namelist_defaults.xml is kinda hopeless
echo "POP2"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/components/pop/cime_config/config_component.xml --comp POP2 --htmlfile $OUTPUT/pop2_input.html --comptag pop2_cesm2_0_rel_n02

# RTM UPDATED
echo "RTM"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/components/rtm/cime_config/config_component.xml --comp RTM --htmlfile $OUTPUT/rtm_input.html --comptag release-cesm2.0.00

# WW3 UPDATED
echo "WW3"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/components/ww3/cime_config/config_component.xml --comp WW3 --htmlfile $OUTPUT/ww3_input.html --comptag ww3_cesm2_0_rel_01

###### data model namelists

# DATM NOT UPDATED AS NOT IN OG
echo "SKIPPING DATM"
#./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/cime/src/components/data_comps/datm/cime_config/config_component.xml --comp DATM --htmlfile $OUTPUT/datm_input.html --comptag cime5.6.19 --compversion 2.1

# DESP UPDATED
echo "DESP"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/cime/src/components/data_comps/desp/cime_config/config_component.xml --comp DESP --htmlfile $OUTPUT/desp_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# DICE UPDATED
echo "DICE"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/cime/src/components/data_comps/dice/cime_config/config_component.xml --comp DICE --htmlfile $OUTPUT/dice_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# DLND UPDATED
echo "DLND"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/cime/src/components/data_comps/dlnd/cime_config/config_component.xml --comp DLND --htmlfile $OUTPUT/dlnd_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# DOCN - required a tweek to the "QOBS" string in DOCN_MODE desc because the quotes were invalid ascii characters
# UPDATED
echo "DOCN"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/cime/src/components/data_comps/docn/cime_config/config_component.xml --comp DOCN --htmlfile $OUTPUT/docn_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# DROF UPDATED
echo "DROF"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/cime/src/components/data_comps/drof/cime_config/config_component.xml --comp DROF --htmlfile $OUTPUT/drof_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# DWAV UPDATED
echo "DWAV"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/cime/src/components/data_comps/dwav/cime_config/config_component.xml --comp DWAV --htmlfile $OUTPUT/dwav_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# Driver UPDATED
echo "DRIVER"
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/cime/src/drivers/mct/cime_config/config_component.xml --comp Driver --htmlfile $OUTPUT/drv_input.html --comptag cime_cesm2_0_rel_03
# Driver input cesm UPDATED
./compinputdef2html.py --cesmmodel 2.0.0 --inputfile $CESMROOT/cime/src/drivers/mct/cime_config/config_component_cesm.xml --comp Driver --htmlfile $OUTPUT/drv_input_cesm.html --comptag cime_cesm2_0_rel_03
