#!/bin/sh

export CIMEROOT=/home/ryanj/scripts/cesm2.0.0/cime
CESMROOT=/home/ryanj/scripts/cesm2.0.0
OUTROOT=/home/ryanj/scripts/CESM_xml2html/toss

# CAM UPDATED
echo "CAM"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/components/cam/bld/namelist_files/namelist_definition.xml --comp CAM --htmlfile $OUTROOT/cam_nml.html --comptag cam_cesm2_0_rel_02 --compversion 6.0

# CICE UPDATED
echo "CICE"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/components/cice/cime_config/namelist_definition_cice.xml --comp CICE --htmlfile $OUTROOT/cice_nml.html --comptag cice5_cesm2_0_rel_01  --compversion 5.0

# CISM UPDATED
echo "CISM"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/components/cism/bld/namelist_files/namelist_definition_cism.xml --comp CISM --htmlfile $OUTROOT/cism_nml.html --comptag release-cesm2.0.01

# CLM
# had to remove one & manually in input namelist file for clm4_5
# also desc elements, need to be pre formatted in order to wrap correctly in the data table

# NOT UPDATED clm5_0_nml.html not in 2.0.0
echo "SKIPPING CLM5"
#./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/components/clm/bld/namelist_files/namelist_definition_clm4_5.xml --comp CLM --htmlfile $OUTROOT/clm5_0_nml.html --comptag release-clm5.0.25
# CLM4 UPDATED
echo "CLM4"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/components/clm/bld/namelist_files/namelist_definition_clm4_0.xml --comp CLM --htmlfile $OUTROOT/clm4_0_nml.html --comptag clm4.0.81
# CLM4.5 UPDATED
echo "CLM4.5"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/components/clm/bld/namelist_files/namelist_definition_clm4_5.xml --comp CLM --htmlfile $OUTROOT/clm4_5_nml.html --comptag release-clm5.0.0

# MARBL NOT UPDATE - MANUAL UPDATE OF HTML
# need to run the $MARBLROOT/MARBL_tools/yaml_to_json.py script first
echo "SKIPPING MARBL"
# ./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/components/pop/externals/MARBL/defaults/json/settings_latest.json --comp MARBL --htmlfile $OUTROOT/marbl_nml.html --comptag cesm2.1-n00 --marbl-json

# MOSART UPDATED
echo "MOSART"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/components/mosart/cime_config/namelist_definition_mosart.xml --comp MOSART --htmlfile $OUTROOT/mosart_nml.html --comptag release-cesm2.0.00

# POP2 NOT UPDATED - MANUAL UPDATE OF HTML
echo "SKIPPING POP"
# pop namelist required *a lot* of manual edits to get it to parse through the CIME tools and namelist_defaults.xml is kinda hopeless
# ./nmldef2html.py --cesmmodel 2.0.0 --nmlfile ./pop_namelist_files/namelist_definition_pop.xml --comp POP2 --htmlfile $OUTROOT/pop2_nml.html --comptag pop2_cesm2_1_rel_n06

# RTM UPDATED
echo "RTM"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/components/rtm/cime_config/namelist_definition_rtm.xml --comp RTM --htmlfile $OUTROOT/rtm_nml.html --comptag release-cesm2.0.00

# WW3 UPDATED
echo "WW3"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/components/ww3/cime_config/namelist_definition_ww3.xml --comp WW3 --htmlfile $OUTROOT/ww3_nml.html --comptag ww3_cesm2_0_rel_01

###### data model namelists

# DATM UPDATED
echo "DATM"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/cime/src/components/data_comps/datm/cime_config/namelist_definition_datm.xml --comp DATM --htmlfile $OUTROOT/datm_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# DESP UPDATED
echo "DESP"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/cime/src/components/data_comps/desp/cime_config/namelist_definition_desp.xml --comp DESP --htmlfile $OUTROOT/desp_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# DICE UPDATED
echo "DICE"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/cime/src/components/data_comps/dice/cime_config/namelist_definition_dice.xml --comp DICE --htmlfile $OUTROOT/dice_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# DLND UPDATED
echo "DLND"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/cime/src/components/data_comps/dlnd/cime_config/namelist_definition_dlnd.xml --comp DLND --htmlfile $OUTROOT/dlnd_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# DOCN UPDATED
echo "DOCN"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/cime/src/components/data_comps/docn/cime_config/namelist_definition_docn.xml --comp DOCN --htmlfile $OUTROOT/docn_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# DROF UPDATED
echo "DROF"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/cime/src/components/data_comps/drof/cime_config/namelist_definition_drof.xml --comp DROF --htmlfile $OUTROOT/drof_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# DWAV UPDATED
echo "DWAV"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/cime/src/components/data_comps/dwav/cime_config/namelist_definition_dwav.xml --comp DWAV --htmlfile $OUTROOT/dwav_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# Driver UPDATED
echo "Driver"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/cime/src/drivers/mct/cime_config/namelist_definition_drv.xml --comp Driver --htmlfile $OUTROOT/drv_nml.html --comptag cime_cesm2_0_rel_03
# Driver fields UPDATED
echo "Driver fields"
./nmldef2html.py --cesmmodel 2.0.0 --nmlfile $CESMROOT/cime/src/drivers/mct/cime_config/namelist_definition_drv_flds.xml --comp Driver --htmlfile $OUTROOT/drv_fields_nml.html --comptag cime_cesm2_0_rel_03
